# Generated by Django 4.2.4 on 2024-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_email', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=200)),
                ('patient_message', models.TextField()),
                ('booked_date', models.DateField(verbose_name='date booked')),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
